### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by daudfauzy98** [dianrahmaji/digitalent-be-23#1]
Mas Dian, ini errornya kenapa ya? Saya cek di file antrian.go dan handler.go di line yang dimaksud, sudah sama seperti punya masnya..

![Error 04](https://user-images.githubusercontent.com/71966505/97858114-426d6280-1d31-11eb-9376-c5029e880444.jpg)

**Comment by dianrahmaji** [comment]
Boleh minta full codenya, Mas?

**Comment by daudfauzy98** [comment]
Ini link Github kodingannya mas, [https://github.com/daudfauzy98/Pengenalan-Konsep-MVC](url)

**Comment by daudfauzy98** [comment]
Terima kasih mas, kodingnnya udah ngga error lagi. Ternyata masalahnya ada di fungsi `initDB()` di file `config.go`, seharunya ditulis `init()` saja.
